In [1]:
import pandas as pd
import subprocess
data = pd.read_csv('Dataset.csv', sep=';')
data = data.reset_index()
data

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
0,0,https://www.olx.pl/d/oferta/wynajem-pokoju-poz...,1170,23,4,10,200,1100
1,1,https://www.olx.pl/d/oferta/wynajem-pokoju-poz...,1070,23,4,8,200,1000
2,2,https://www.olx.pl/d/oferta/wynajme-maly-pokoj...,690,43,5,8,0,690
3,3,https://www.olx.pl/d/oferta/pokoj-do-wynajecia...,900,43,4,14,0,900
4,4,https://www.olx.pl/d/oferta/na-wynajem-pokoj-1...,1150,104,7,15,0,1100
5,5,https://www.olx.pl/d/oferta/pokoj-wynajem-pozn...,1700,20,4,10,0,1600
6,6,https://www.olx.pl/d/oferta/pokoj-na-wynajem-u...,1100,63,8,9,0,1100
7,7,https://www.olx.pl/d/oferta/wynajem-pokoju-na-...,900,41,3,14,0,900
8,8,https://www.olx.pl/d/oferta/wynajme-pokoj-na-o...,970,55,5,14,0,900
9,9,https://www.olx.pl/d/oferta/piekny-pokoj-do-wy...,900,47,6,7,300,700
10,10,https://www.olx.pl/d/oferta/pokoj-10m2-na-wyna...,1350,61,1,10,0,1350
11,11,https://www.olx.pl/d/oferta/pokoj-na-wynajem-o...,1250,99,7,12,0,1250
12,12,https://www.olx.pl/d/oferta/pokoj-na-wynajem-o...,1100,99,7,9,0,1100
13,13,https://www.olx.pl/d/oferta/wynajem-pokoju-od-...,750,46,3,11,0,600
14,14,https://www.olx.pl/d/oferta/pokoj-na-wynajem-w...,1100,58,6,16,250,600
15,15,https://www.olx.pl/d/oferta/duzy-pokoj-w-centr...,1150,26,4,15,300,1100
16,16,https://www.olx.pl/d/oferta/pokoj-na-armii-kra...,1150,48,5,8,0,600
17,17,https://www.olx.pl/d/oferta/pokoj-na-glogowski...,1100,54,4,8,300,1000
18,18,https://www.otodom.pl/pl/oferta/nowe-przytulne...,1350,81,9,11,0,1350
19,19,https://www.olx.pl/d/oferta/pokoj-jednoosobowy...,950,115,7,8,0,950
20,20,https://www.olx.pl/d/oferta/pokoj-jednoosobowy...,1600,36,1,15,0,1400
21,21,https://www.olx.pl/d/oferta/pokoj-jednoosobowy...,1280,22,5,10,200,100

In [2]:
random_pairs = [data.sample(n=2, random_state=i)[['Link']] for i in range(20)]
random_pairs += [data.iloc[[13, 20]][['Link']]]
random_pairs+=[data.iloc[[7, 18]][['Link']]]
random_pairs+=[data.iloc[[8, 15]][['Link']]]
random_pairs+=[data.iloc[[15, 20]][['Link']]]
random_pairs+=[data.iloc[[20, 8]][['Link']]]

global_edge = False
global_dataframe = True

def test_pair(pair_index):
    p = random_pairs[pair_index]

    for url in p["Link"].dropna().unique():
        if global_edge:
            subprocess.Popen(f'start msedge "{url}"', shell=True)

        row = data[data['Link'] == url]
        if global_dataframe:
            display(row)

    return p

preferences = []

In [3]:
pair = test_pair(0)
winner = data[data['index'] == 10]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
20,20,https://www.olx.pl/d/oferta/pokoj-jednoosobowy...,1600,36,1,15,0,1400

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
10,10,https://www.olx.pl/d/oferta/pokoj-10m2-na-wyna...,1350,61,1,10,0,1350

In [4]:
pair = test_pair(1)
winner = data[data['index'] == 16]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
19,19,https://www.olx.pl/d/oferta/pokoj-jednoosobowy...,950,115,7,8,0,950

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
16,16,https://www.olx.pl/d/oferta/pokoj-na-armii-kra...,1150,48,5,8,0,600

In [5]:
pair = test_pair(3)
winner = data[data['index'] == 13]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
20,20,https://www.olx.pl/d/oferta/pokoj-jednoosobowy...,1600,36,1,15,0,1400

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
13,13,https://www.olx.pl/d/oferta/wynajem-pokoju-od-...,750,46,3,11,0,600

In [6]:
pair = test_pair(6)
winner = data[data['index'] == 7]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
19,19,https://www.olx.pl/d/oferta/pokoj-jednoosobowy...,950,115,7,8,0,950

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
7,7,https://www.olx.pl/d/oferta/wynajem-pokoju-na-...,900,41,3,14,0,900

In [7]:
pair = test_pair(8)
winner = data[data['index'] == 7]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
6,6,https://www.olx.pl/d/oferta/pokoj-na-wynajem-u...,1100,63,8,9,0,1100

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
7,7,https://www.olx.pl/d/oferta/wynajem-pokoju-na-...,900,41,3,14,0,900

In [8]:
pair = test_pair(9)
winner = data[data['index'] == 9]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
4,4,https://www.olx.pl/d/oferta/na-wynajem-pokoj-1...,1150,104,7,15,0,1100

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
9,9,https://www.olx.pl/d/oferta/piekny-pokoj-do-wy...,900,47,6,7,300,700

In [9]:
pair = test_pair(12)
winner = data[data['index'] == 7]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
7,7,https://www.olx.pl/d/oferta/wynajem-pokoju-na-...,900,41,3,14,0,900

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
10,10,https://www.olx.pl/d/oferta/pokoj-10m2-na-wyna...,1350,61,1,10,0,1350

In [10]:
pair = test_pair(20)
winner = data[data['index'] == 13]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
13,13,https://www.olx.pl/d/oferta/wynajem-pokoju-od-...,750,46,3,11,0,600

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
20,20,https://www.olx.pl/d/oferta/pokoj-jednoosobowy...,1600,36,1,15,0,1400

In [11]:
pair = test_pair(21)
winner = data[data['index'] == 7]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
7,7,https://www.olx.pl/d/oferta/wynajem-pokoju-na-...,900,41,3,14,0,900

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
18,18,https://www.otodom.pl/pl/oferta/nowe-przytulne...,1350,81,9,11,0,1350

In [12]:
pair = test_pair(22)
winner = data[data['index'] == 8]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
8,8,https://www.olx.pl/d/oferta/wynajme-pokoj-na-o...,970,55,5,14,0,900

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
15,15,https://www.olx.pl/d/oferta/duzy-pokoj-w-centr...,1150,26,4,15,300,1100

In [13]:
pair = test_pair(23)
winner = data[data['index'] == 15]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
15,15,https://www.olx.pl/d/oferta/duzy-pokoj-w-centr...,1150,26,4,15,300,1100

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
20,20,https://www.olx.pl/d/oferta/pokoj-jednoosobowy...,1600,36,1,15,0,1400

In [14]:
pair = test_pair(24)
winner = data[data['index'] == 20]['Link'].values[0]
relation = '>' if winner == pair.iloc[0]['Link'] else '<'
preferences.append((pair.iloc[0]['Link'], pair.iloc[1]['Link'], relation))

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
20,20,https://www.olx.pl/d/oferta/pokoj-jednoosobowy...,1600,36,1,15,0,1400

,index,Link,Price per month (total),Distance from CW (minutes walking),Distance from bus/tram stop (min walk),Area of room (m^2),Parking price,Security deposit
8,8,https://www.olx.pl/d/oferta/wynajme-pokoj-na-o...,970,55,5,14,0,900

In [15]:
for i in preferences:
    print(i)
with open('preferences.csv', 'w') as f:    
    f.write("Link1;Link2;Relation\n")
    for item in preferences:
        f.write(f"{item[0]};{item[1]};{item[2]}\n")

('https://www.olx.pl/d/oferta/pokoj-jednoosobowy-w-sercu-lazarza-z-balkonem-CID3-ID19S2pW.html?search_reason=search%7Cpromoted', 'https://www.olx.pl/d/oferta/pokoj-10m2-na-wynajem-os-zwyciestwa-CID3-ID19Wjl1.html?search_reason=search%7Corganic', '<')
('https://www.olx.pl/d/oferta/pokoj-jednoosobowy-bezposrednio-CID3-ID19RmlO.html?search_reason=search%7Cpromoted', 'https://www.olx.pl/d/oferta/pokoj-na-armii-krajowej-czysty-spokojne-mieszkanie-hoca1-CID3-ID17BkJV.html?search_reason=search%7Corganic', '<')
('https://www.olx.pl/d/oferta/pokoj-jednoosobowy-w-sercu-lazarza-z-balkonem-CID3-ID19S2pW.html?search_reason=search%7Cpromoted', 'https://www.olx.pl/d/oferta/wynajem-pokoju-od-zaraz-stare-zegrze-29-CID3-ID19Wyt2.html?search_reason=search%7Corganic', '<')
('https://www.olx.pl/d/oferta/pokoj-jednoosobowy-bezposrednio-CID3-ID19RmlO.html?search_reason=search%7Cpromoted', 'https://www.olx.pl/d/oferta/wynajem-pokoju-na-ratajach-CID3-ID19Sp6i.html?search_reason=search%7Cpromoted', '<')
('https://www.olx.pl/d/oferta/pokoj-na-wynajem-ul-kolejowa-CID3-ID19TS6I.html?search_reason=search%7Cpromoted', 'https://www.olx.pl/d/oferta/wynajem-pokoju-na-ratajach-CID3-ID19Sp6i.html?search_reason=search%7Cpromoted', '<')
('https://www.olx.pl/d/oferta/na-wynajem-pokoj-1-osobowy-piatkowie-dla-dziewczyny-wolne-od-zaraz-CID3-ID19QRV2.html?search_reason=search%7Cpromoted', 'https://www.olx.pl/d/oferta/piekny-pokoj-do-wynajecia-w-centrum-pl-asnyka-CID3-ID16FvNT.html?search_reason=search%7Corganic', '<')
('https://www.olx.pl/d/oferta/wynajem-pokoju-na-ratajach-CID3-ID19Sp6i.html?search_reason=search%7Cpromoted', 'https://www.olx.pl/d/oferta/pokoj-10m2-na-wynajem-os-zwyciestwa-CID3-ID19Wjl1.html?search_reason=search%7Corganic', '>')
('https://www.olx.pl/d/oferta/wynajem-pokoju-od-zaraz-stare-zegrze-29-CID3-ID19Wyt2.html?search_reason=search%7Corganic', 'https://www.olx.pl/d/oferta/pokoj-jednoosobowy-w-sercu-lazarza-z-balkonem-CID3-ID19S2pW.html?search_reason=search%7Cpromoted', '>')
('https://www.olx.pl/d/oferta/wynajem-pokoju-na-ratajach-CID3-ID19Sp6i.html?search_reason=search%7Cpromoted', 'https://www.otodom.pl/pl/oferta/nowe-przytulne-komfortowe-4-pokoje-na-wynajem-ID4yGD0', '>')
('https://www.olx.pl/d/oferta/wynajme-pokoj-na-os-winogrady-CID3-ID187JTO.html?search_reason=search%7Corganic', 'https://www.olx.pl/d/oferta/duzy-pokoj-w-centrum-poznania-CID3-ID19Wd36.html?search_reason=search%7Cpromoted', '>')
('https://www.olx.pl/d/oferta/duzy-pokoj-w-centrum-poznania-CID3-ID19Wd36.html?search_reason=search%7Cpromoted', 'https://www.olx.pl/d/oferta/pokoj-jednoosobowy-w-sercu-lazarza-z-balkonem-CID3-ID19S2pW.html?search_reason=search%7Cpromoted', '>')
('https://www.olx.pl/d/oferta/pokoj-jednoosobowy-w-sercu-lazarza-z-balkonem-CID3-ID19S2pW.html?search_reason=search%7Cpromoted', 'https://www.olx.pl/d/oferta/wynajme-pokoj-na-os-winogrady-CID3-ID187JTO.html?search_reason=search%7Corganic', '>')